// Code generated by tygo. DO NOT EDIT.
// This file is generated by tygo from internal/api/types.go.
// Do not edit by hand. Run `make types` to regenerate.

//////////
// source: types.go
/*
Package api defines the HTTP wire types for hmi-update.

This file is the source of truth that tygo reads to regenerate
ui/src/lib/types.d.ts (see tygo.yaml at repo root, and `make types`).

The field tags here must mirror internal/state/Container so that what the
store persists to ./hmi_update_state.json deserializes cleanly into the
same wire shape served by GET /api/state. Plan 04 will reconcile by
re-using or aliasing one in terms of the other; field tags being
identical is the load-bearing invariant.

Do NOT import internal/state from this file — tygo's package read should
be self-contained, and we want this file to remain editable without
pulling in runtime concerns.
*/

/**
 * Container is the on-the-wire representation of a watched Docker container.
 * Field tags mirror internal/state/Container verbatim. `omitempty` on
 * optional string fields prevents zero-value pollution of the JSON payload
 * served to the UI.
 * Phase 2 plan 02-01 adds ContainerID, Labels, Pinned, Stopped — see
 * internal/state/schema.go for the field-by-field rationale. The tags
 * here are byte-identical to state.Container; tygo regenerates the
 * TypeScript Container interface from this file (tygo.yaml include_files
 * limits the scan to types.go).
 * Phase 3 plan 03-01 adds AvailableDigest, LastPolledAt, Notes mirroring
 * state.Container. Time fields use `omitzero` (Go 1.24+) because
 * encoding/json's `omitempty` does not recognize the time.Time struct
 * zero value — without omitzero, an un-polled container would serialize
 * "last_polled_at":"0001-01-01T00:00:00Z" and break the Phase 2
 * forward-compat invariant. See state.Container.LastPolledAt godoc.
 * Phase 4 plan 04-01 adds ActionInFlight, ActionError mirroring
 * state.Container. Both are `omitempty` strings; tags byte-identical
 * to state.Container; verified by TestPhase4Types_StateApiTagParity.
 */
export interface Container {
  service: string;
  image?: string;
  tag?: string;
  current_digest?: string;
  previous_digest?: string;
  update_available: boolean;
  /**
   * ContainerID is the short 12-char docker container id (matches
   * `docker ps`). Discovery goroutine (plan 02-03) sets this.
   */
  container_id?: string;
  /**
   * Labels carries the hmi-update.* labels relevant to update/rollback
   * policy (watch, tag-pattern, allow-update, allow-rollback). Filtered
   * at the discovery layer.
   */
  labels?: { [key: string]: string};
  /**
   * Pinned is true for digest-pinned image references (image: ...@sha256:...).
   * The Phase 5 UI renders these as "pinned: opt-out"; Phase 3's poller
   * skips them.
   */
  pinned?: boolean;
  /**
   * Stopped is true when the container's most recent docker event was
   * `die`. The Phase 5 UI shows a stopped-status badge; Phase 3's
   * poller skips these (no digest to compare).
   */
  stopped?: boolean;
  /**
   * AvailableDigest is the upstream sha256 most recently fetched by the
   * poll loop. See internal/state.Container.AvailableDigest for the
   * semantic rationale (DETECT-05/DETECT-07).
   */
  available_digest?: string;
  /**
   * LastPolledAt is RFC3339Nano-encoded wall-clock time of the most
   * recent successful resolver.Digest call. See state.Container.
   * Tag is `omitzero` (not `omitempty`) — see file-level godoc.
   */
  last_polled_at?: string /* RFC3339 */;
  /**
   * Notes is a single short ops-readable sentence (pinned, invalid
   * pattern, etc.). See state.Container.Notes for the full set.
   */
  notes?: string;
  /**
   * ActionInFlight is the current in-flight per-row action (Phase 4).
   * See internal/state.Container.ActionInFlight for full semantics.
   */
  action_in_flight?: string;
  /**
   * ActionError is the last action's failure surface (Phase 4). See
   * internal/state.Container.ActionError for the full format.
   */
  action_error?: string;
}
/**
 * State is the top-level wire schema served at GET /api/state.
 * Version is the on-disk schema version (currently 1 — see brief §F4).
 * Containers is keyed by compose service name.
 * Phase 3 plan 03-01 adds LastPollStart, LastPollEnd, LastPollError —
 * the poll-loop observability surface. See internal/state.State for the
 * full semantics. Surfaced in /api/state for the Phase 5 UI's "last
 * polled" indicator. Time fields use `omitzero` (NOT `omitempty`) so a
 * pre-first-tick payload omits the keys cleanly.
 */
export interface State {
  version: number /* int */;
  containers: { [key: string]: Container};
  /**
   * LastPollStart / LastPollEnd / LastPollError — see internal/state.State
   * for full semantics. Surfaced in /api/state for the Phase 5 UI's
   * "last polled" indicator.
   */
  last_poll_start?: string /* RFC3339 */;
  last_poll_end?: string /* RFC3339 */;
  last_poll_error?: string;
}
