// Code generated by tygo. DO NOT EDIT.
// This file is generated by tygo from internal/api/types.go.
// Do not edit by hand. Run `make types` to regenerate.

//////////
// source: types.go
/*
Package api defines the HTTP wire types for hmi-update.

This file is the source of truth that tygo reads to regenerate
ui/src/lib/types.d.ts (see tygo.yaml at repo root, and `make types`).

The field tags here must mirror internal/state/Container so that what the
store persists to ./hmi_update_state.json deserializes cleanly into the
same wire shape served by GET /api/state. Plan 04 will reconcile by
re-using or aliasing one in terms of the other; field tags being
identical is the load-bearing invariant.

Do NOT import internal/state from this file — tygo's package read should
be self-contained, and we want this file to remain editable without
pulling in runtime concerns.
*/

/**
 * Container is the on-the-wire representation of a watched Docker container.
 * Field tags mirror internal/state/Container verbatim. `omitempty` on
 * optional string fields prevents zero-value pollution of the JSON payload
 * served to the UI.
 */
export interface Container {
  service: string;
  image?: string;
  tag?: string;
  current_digest?: string;
  previous_digest?: string;
  update_available: boolean;
}
/**
 * State is the top-level wire schema served at GET /api/state.
 * Version is the on-disk schema version (currently 1 — see brief §F4).
 * Containers is keyed by compose service name.
 */
export interface State {
  version: number /* int */;
  containers: { [key: string]: Container};
}
